export const pData = [
    {
        id:1,
        image:"images/image1.jpeg",
        name:'Bedsheet1',
        category:'bedsheet',
        price:'100',
        describe:'dcfvghbnjmkcfvghbjnkrtvgbhjnkm'
    },
    {
        id:2,
        image:"images/image2.jpeg",
        name:'Doremate',
        category:'doremate',
        price:'150',
        describe:'dcfvghbnjmkcfvghbjnkrtvgbhjnkm'
    },
    {
        id:3,
        image:"images/image3.jpeg",
        name:'Curtoon',
        category:'curtoon',
        price:'100',
        describe:'dcfvghbnjmkcfvghbjnkrtvgbhjnkm'
    },
    {
        id:4,
        image:"images/image4.jpeg",
        name:'Pillow3',
        category:'pillow',
        price:'450',
        describe:'dcfvghbnjmkcfvghbjnkrtvgbhjnkm'
    },
    {
        id:5,
        image:"images/image3.jpeg",
        name:'Curtoon',
        category:'curtoon',
        price:'100',
        describe:'dcfvghbnjmkcfvghbjnkrtvgbhjnkm'
    },
    {
        id:6,
        image:"images/image3.jpeg",
        name:'Pillow2',
        category:'pillow',
        price:'100',
        describe:'dcfvghbnjmkcfvghbjnkrtvgbhjnkm'
    },
    {
        id:7,
        image:"images/image3.jpeg",
        name:'Curtoon2',
        category:'curtoon',
        price:'190',
        describe:'dcfvghbnjmkcfvghbjnkrtvgbhjnkm'
    },
    {
        id:8,
        image:"images/image3.jpeg",
        name:'Bedsheet2',
        category:'bedsheet',
        price:'250',
        describe:'dcfvghbnjmkcfvghbjnkrtvgbhjnkm'
    },
];