import image1 from '../images/image1.jpeg';
import image2 from '../images/image2.jpeg';
import image3 from '../images/image3.jpeg';
import image4 from '../images/image4.jpeg';

export const pData = [
    {
        id:1,
        image:image1,
        name:'Bedsheet1',
        category:'bedsheet',
        price:'100',
        describe:'dcfvghbnjmkcfvghbjnkrtvgbhjnkm'
    },
    {
        id:2,
        image:image2,
        name:'Doremate',
        category:'doremate',
        price:'150',
        describe:'dcfvghbnjmkcfvghbjnkrtvgbhjnkm'
    },
    {
        id:3,
        image:image3,
        name:'Curtoon',
        category:'curtoon',
        price:'100',
        describe:'dcfvghbnjmkcfvghbjnkrtvgbhjnkm'
    },
    {
        id:4,
        image:image4,
        name:'Pillow3',
        category:'pillow',
        price:'450',
        describe:'dcfvghbnjmkcfvghbjnkrtvgbhjnkm'
    },
    {
        id:5,
        image:image3,
        name:'Curtoon',
        category:'curtoon',
        price:'100',
        describe:'dcfvghbnjmkcfvghbjnkrtvgbhjnkm'
    },
    {
        id:6,
        image:image3,
        name:'Pillow2',
        category:'pillow',
        price:'100',
        describe:'dcfvghbnjmkcfvghbjnkrtvgbhjnkm'
    },
    {
        id:7,
        image:image3,
        name:'Curtoon2',
        category:'curtoon',
        price:'190',
        describe:'dcfvghbnjmkcfvghbjnkrtvgbhjnkm'
    },
    {
        id:8,
        image:image3,
        name:'Bedsheet2',
        category:'bedsheet',
        price:'250',
        describe:'dcfvghbnjmkcfvghbjnkrtvgbhjnkm'
    },
];